### ISSUE TITLE
Prepare beta milestone

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#628]
- [x] Clean up irrelevant issues
- [x] Re-evaluate beta-gamma-rho distribution of issues
- [x] Add category and priority to issues
- [x] Add sprints and set deadlines (take into account workshops)
- [ ] ~~Plan brainstorm meetings to refine features~~
